{
 "title": "MetricZ Player",
 "description": "Per player detailed stats for MetricZ",
 "tags": [
  "dayz",
  "metricz"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status{instance=~\"$instance\"},world)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},instance_id)"
    }
   },
   {
    "name": "steam_id",
    "label": "Steam ID",
    "query": {
     "query": "label_values(dayz_metricz_player_loaded,steam_id)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   {
    "name": "gender",
    "label": "Gender",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   {
    "name": "guid",
    "label": "GUID",
    "query": {
     "query": "label_values(dayz_metricz_player_loaded{steam_id=\"$steam_id\"},guid)"
    }
   },
   {
    "name": "buid",
    "label": "BUID",
    "query": {
     "query": "label_values(dayz_metricz_player_loaded{steam_id=\"$steam_id\"},buid)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(metricz_rcon_player_joined{buid=\"$buid\"},ip)"
    }
   },
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(metricz_rcon_player_joined{buid=\"$buid\"},country)"
    }
   },
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "label_values(metricz_rcon_player_joined{buid=\"$buid\"},city)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   {
    "name": "blood",
    "label": "Blood",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   { "name": "map_tiles_layer", "label": "Map Tiles Layer", "query": "topographic,satellite" },
   {
    "name": "map_tiles_url",
    "label": "Map Tiles URL",
    "query": "https://dzmap.woozymasta.ru/maps"
   }
  ]
 },
 "panels": [
  {
   "title": "Player Info",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "![${type}](https://raw.githubusercontent.com/WoozyMasta/metricz/refs/heads/master/avatars/${type}.png)\n\n## Player: [${name}](https://steamcommunity.com/profiles/${steam_id})\n\n* ${type} (${gender}) blood: ${blood}\n* Steam ID: `${steam_id}`  \n* GUID: `${guid}`  \n* BUID: `${buid}`\n* IP: `${ip}` [${country}:${city}]"
   }
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_health{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blood",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_blood{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shock",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_shock{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_lifetime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"})\r\nor\r\nmax by (steam_id) (last_over_time(dayz_metricz_player_lifetime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_energy{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Water",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_water{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_agents_active{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players Killed Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (steam_id) (increase(dayz_metricz_player_stat_players_killed_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longest Survivor Hit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (increase(dayz_metricz_player_stat_longest_survivor_hit_m{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_temperature_celsius{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bleeding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_bleeding_active{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": ")"
    }
   ]
  },
  {
   "title": "Toxicity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_toxicity{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players List",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "group by(steam_id, name) (dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{ world }} ({{ instance_id }}) - {{ steam_id }}"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_weight{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wetness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_wetness{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconscious",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_unconscious{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infected Killed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (steam_id) (increase(dayz_metricz_player_stat_infected_killed_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distance Traveled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (steam_id) (increase(dayz_metricz_player_stat_distance_meters{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immunity Boosted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_immunity_boosted{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "God Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_godmode{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restrained",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_restrained{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Ping",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "min by (steam_id) (dayz_metricz_player_network_ping_min{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max by (steam_id) (dayz_metricz_player_network_ping_max{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network Throttle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (steam_id) (dayz_metricz_player_network_throttle{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "throttle"
    }
   ]
  },
  {
   "title": "Life Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_stat_playtime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}\r\nor\r\nlast_over_time(dayz_metricz_player_stat_playtime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}[$__range])",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_position_y{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Session Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by (steam_id, type, world) (dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"})",
     "legendFormat": "{{type}} ({{ world }})"
    }
   ]
  },
  {
   "title": "Players HeatMap",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "metricz_rcon_player_lat{instance=~\"$instance\", instance_id=~\"$instance_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "metricz_rcon_player_lon{instance=~\"$instance\", instance_id=~\"$instance_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player Sessions by IP",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "count by (ip, city, country) (metricz_rcon_player_joined{instance=~\"$instance\", instance_id=~\"$instance_id\", buid=~\"$buid\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}