{
 "title": "MetricZ Server",
 "description": "Per server detailed stats for MetricZ",
 "tags": [
  "dayz",
  "metricz"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{instance=\"$instance\"},instance_id)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status{instance_id=\"$instance_id\", instance=\"$instance\"},world)"
    }
   },
   {
    "name": "save_version",
    "label": "Save Version",
    "query": {
     "query": "label_values(dayz_metricz_status{instance_id=\"$instance_id\", instance=\"$instance\"},save_version)"
    }
   },
   {
    "name": "game_version",
    "label": "Game Version",
    "query": {
     "query": "label_values(dayz_metricz_status{instance_id=\"$instance_id\", instance=\"$instance\"},game_version)"
    }
   },
   {
    "name": "map_tiles_name",
    "label": "Map Tiles Name",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},map_tiles_name)"
    }
   },
   {
    "name": "map_tiles_version",
    "label": "Map Tiles Version",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},map_tiles_version)"
    }
   },
   {
    "name": "map_tiles_format",
    "label": "Map Tiles Format",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},map_tiles_format)"
    }
   },
   { "name": "map_tiles_layer", "label": "Map Tiles Layer", "query": "topographic,satellite" },
   {
    "name": "map_tiles_url",
    "label": "Map Tiles URL",
    "query": "https://static.xam.nu/dayz/maps"
   },
   { "name": "player_dash", "label": "Map Tiles URL", "query": "cf1vdc82xx1q8e" },
   {
    "name": "scrape_interval",
    "label": "Scrape Interval",
    "query": {
     "query": "query_result(dayz_metricz_scrape_interval_seconds{instance=\"$instance\", instance_id=\"$instance_id\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(instance_id, world) (dayz_metricz_status{instance=\"$instance\", instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Average Server FPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (dayz_metricz_fps_window_avg{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Update Duration",
   "type": "stat",
   "description": "Metrics update duration in game server",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (dayz_metricz_update_duration_seconds{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Metrics Skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_scrape_skipped_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Interval",
   "type": "stat",
   "description": "Metrics scrape interval in game server",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (dayz_metricz_scrape_interval_seconds{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Date and Weather",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Game Date and Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_game_time_unix_seconds{instance=\"$instance\",instance_id=\"$instance_id\"} * 1000",
       "legendFormat": "{{world}}"
      }
     ]
    },
    {
     "title": "Feels Like",
     "type": "stat",
     "description": "Point in center of world with overcast, wind and fog components",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_temperature{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}}"
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_wind_speed{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}}"
      }
     ]
    },
    {
     "title": "Clouds",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_clouds{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}}"
      }
     ]
    },
    {
     "title": "Time of Day",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_time_of_day{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}}"
      }
     ]
    },
    {
     "title": "Game version",
     "type": "text",
     "description": "Game version (save version)",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
     "options": {
      "content": "# ⚙️ ${game_version}\r\n# 💾 ${save_version}\r\n# 🗺️ ${world}"
     }
    },
    {
     "title": "Temperature",
     "type": "stat",
     "description": "Base world temperature",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_temperature_base{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}}"
      }
     ]
    },
    {
     "title": "Wind Direction",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_wind_direction{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rain/Snow",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min(dayz_metricz_weather_rain{instance=\"$instance\",instance_id=\"$instance_id\"}, 0.0001)",
       "legendFormat": "rain"
      },
      {
       "expr": "clamp_min(dayz_metricz_weather_snow{instance=\"$instance\",instance_id=\"$instance_id\"}, 0.0001)",
       "legendFormat": "snow"
      }
     ]
    },
    {
     "title": "Fog",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_fog{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}}"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Player Spawns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Spawn" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_players_spawns_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Player Corpses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Corpses" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (dayz_metricz_corpses{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players Alive Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Players" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (dayz_metricz_players_online{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    },
    {
     "expr": "sum by (instance_id, world) (dayz_metricz_max_players{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Player Deaths Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Death" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_players_deaths_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Items",
   "type": "stat",
   "description": "Total items (ItemBase) in the world",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_items{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Transport",
   "type": "stat",
   "description": "Total cars, boats and helicopters in the world",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=\"$instance\",instance_id=\"$instance_id\"} + dayz_metricz_boats{instance=\"$instance\",instance_id=\"$instance_id\"} + dayz_metricz_helicopters{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Infected",
   "type": "stat",
   "description": "ZombieBase",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_infected{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Animals",
   "type": "stat",
   "description": "AnimalBase",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_animals{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "eAI / NPC",
   "type": "stat",
   "description": "Expansion AI",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_eai{instance=\"$instance\",instance_id=\"$instance_id\"} + dayz_metricz_eai_npc{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Artillery",
   "type": "stat",
   "description": "Artillery barrages on server  \n_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_artillery_barrages_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Areas",
   "type": "stat",
   "description": "Effects Area  \n* contaminated static\n* contaminated dynamic\n* other effect areas",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_effect_areas{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "AI Count",
   "type": "timeseries",
   "description": "Includes dead bodies\n* ZombieBase\n* AnimalBase\n* eAIBase\n* eAINPCBase",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "dayz_metricz_infected{instance=\"$instance\",instance_id=\"$instance_id\"} > 0",
     "legendFormat": "Infected"
    },
    {
     "expr": "dayz_metricz_animals{instance=\"$instance\",instance_id=\"$instance_id\"} > 0",
     "legendFormat": "Animal"
    },
    {
     "expr": "dayz_metricz_eai{instance=\"$instance\",instance_id=\"$instance_id\"} > 0",
     "legendFormat": "eAI"
    },
    {
     "expr": "dayz_metricz_eai_npc{instance=\"$instance\",instance_id=\"$instance_id\"} > 0",
     "legendFormat": "eAI NPC"
    }
   ]
  },
  {
   "title": "AI Deaths Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Deaths" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_infected_deaths_total{instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "infected"
    },
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_animals_deaths_total{instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "animals"
    },
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_eai_deaths_total{instance_id=\"$instance_id\"}[$__range])) > 0",
     "legendFormat": "eAI"
    },
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_eai_npc_deaths_total{instance_id=\"$instance_id\"}[$__range])) > 0",
     "legendFormat": "eAI NPC"
    }
   ]
  },
  {
   "title": "Clothes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_clothes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Food",
   "type": "stat",
   "description": "Total not Ammo Box_Base (NailBox, HeadlightH7_Box) in the world",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_food{instance=\"$instance\",instance_id=\"$instance_id\",food_type=\"\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Bottles",
   "type": "stat",
   "description": "Bottle_Base",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_bottles{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "DeployableContainer_Base (Barrel, SeaChest, WoodenCrate)",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_containers{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Boxes",
   "type": "stat",
   "description": "NailBox, HeadlightH7_Box",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_boxes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Mined Trees",
   "type": "stat",
   "description": "Increment per one action usage  \n_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_mined_trees_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Mined Bushes",
   "type": "stat",
   "description": "Increment per one action usage  \n_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_mined_bushes_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Weapons",
   "type": "stat",
   "description": "Weapon_Base",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weapons{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Magazines",
   "type": "stat",
   "description": "MagazineStorage",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_magazines{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Optics",
   "type": "stat",
   "description": "scopes, rangefinders, binoculars",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_optics{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Suppressors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_suppressors{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Explosives",
   "type": "stat",
   "description": "grenade, flash, smoke, claymore, plastic, improvised",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_explosives{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Mined Rocks",
   "type": "stat",
   "description": "Increment per one action usage  \n_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_mined_rocks_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Gifts Unpacked",
   "type": "stat",
   "description": "_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_gifts_unpacked_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Transport Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "Cars"
    },
    {
     "expr": "dayz_metricz_boats{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "Boats"
    },
    {
     "expr": "dayz_metricz_helicopters{instance=\"$instance\",instance_id=\"$instance_id\"} > 0",
     "legendFormat": "Helicopters"
    }
   ]
  },
  {
   "title": "Transport Destroyed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Destroyed" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_cars_destroyed_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "Cars"
    },
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_boats_destroyed_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "Boats"
    },
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_helicopters_destroyed_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range])) > 0",
     "legendFormat": "Helicopters"
    }
   ]
  },
  {
   "title": "Ammo Boxes",
   "type": "stat",
   "description": "Total Box_Base with Ammo",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_ammo_boxes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Ammo Piles",
   "type": "stat",
   "description": "Ammunition_Base",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_ammo{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Car Wheels",
   "type": "stat",
   "description": "wheels",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_car_wheels{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Car Parts",
   "type": "stat",
   "description": "doors & trunks",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_car_parts{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Tents",
   "type": "stat",
   "description": "TentBase (Shelter, CarTent, LargeTent, PartyTent, MediumTent)",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_tents{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Fish Catched",
   "type": "stat",
   "description": "Success complete fishing action  \n_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_fishing_catches_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Fishing Tries",
   "type": "stat",
   "description": "Starterd fishing action  \n_total counter_",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (instance_id, world) (increase(dayz_metricz_fishing_attempts_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]))",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Base Buildings",
   "type": "stat",
   "description": "BaseBuildingBase (Fence, Watchtower, ShelterSite, TerritoryFlag, etc)",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_base_buildings{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Territory Flag",
   "type": "stat",
   "description": "TerritoryFlag",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_territory_flags{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Gardens",
   "type": "stat",
   "description": "GardenPlot (Dug)",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_gardens{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Stashes",
   "type": "stat",
   "description": "Buried items (DrysackBag, SeaChest, WoodenCrate, FirstAidKit, AmmoBox, Pot, Bear, etc.)",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_stashes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Crash Sites",
   "type": "stat",
   "description": "mi8, uh1y, santa sleigh",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_crash_sites{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Players List",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\"}",
       "legendFormat": "{{ world }} ({{ instance_id }}) - {{ steam_id }}"
      }
     ]
    },
    {
     "title": "Average Ping of all Players",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "min(dayz_metricz_player_network_ping_min{instance=~\"$instance\", instance_id=~\"$instance_id\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(dayz_metricz_player_network_ping_max{instance=~\"$instance\", instance_id=~\"$instance_id\"})",
       "legendFormat": "max"
      },
      {
       "expr": "(\r\n  min(dayz_metricz_player_network_ping_min{instance=~\"$instance\", instance_id=~\"$instance_id\"})\r\n  +\r\n  max(dayz_metricz_player_network_ping_max{instance=~\"$instance\", instance_id=~\"$instance_id\"})\r\n) / 2",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Players Deaths Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "rate(dayz_metricz_players_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\"}[$__rate_interval])",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Weapons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Weapon in World",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 196 },
     "targets": [
      {
       "expr": "dayz_metricz_weapons_by_type{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{weapon}}"
      }
     ]
    },
    {
     "title": "Weapon Shots",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 196 },
     "targets": [
      {
       "expr": "increase(dayz_metricz_weapon_shots_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]) > 0",
       "legendFormat": "{{weapon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kills by Source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player Killed",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 212 },
     "targets": [
      {
       "expr": "increase(dayz_metricz_player_killed_by_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]) > 0",
       "legendFormat": "{{weapon}}"
      }
     ]
    },
    {
     "title": "Creature Killed",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 212 },
     "targets": [
      {
       "expr": "increase(dayz_metricz_creature_killed_by_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]) > 0",
       "legendFormat": "{{weapon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hits by Ammo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player Hits",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 228 },
     "targets": [
      {
       "expr": "increase(dayz_metricz_player_hit_by_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]) > 0",
       "legendFormat": "{{ammo}}"
      }
     ]
    },
    {
     "title": "Creature Hits",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 228 },
     "targets": [
      {
       "expr": "increase(dayz_metricz_creature_hit_by_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__range]) > 0",
       "legendFormat": "{{ammo}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Creatures by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infected Types Total",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 244 },
     "targets": [
      {
       "expr": "sum by(type) (dayz_metricz_infected_by_type{instance=~\"$instance\", instance_id=~\"$instance_id\"} > 0)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Animals Types Total",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 244 },
     "targets": [
      {
       "expr": "sum by(animal) (dayz_metricz_animals_by_type{instance=~\"$instance\", instance_id=~\"$instance_id\"} > 0)",
       "legendFormat": "{{animal}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Territories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Territory Lifetime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "dayz_metricz_territory_lifetime{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{x}}/{{z}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Effect Areas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Effect Area by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "count by (type) (dayz_metricz_effect_area_insiders{instance=\"$instance\",instance_id=\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Effect Area by Class",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "count by (class) (dayz_metricz_effect_area_insiders{instance=\"$instance\",instance_id=\"$instance_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Effect Area Insiders Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 142 },
     "targets": [
      {
       "expr": "dayz_metricz_effect_area_insiders{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{type}} {{ latitude }}/{{ longitude }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC, Events and PathGraph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Events",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(event) (dayz_metricz_events_total{instance=\"$instance\",instance_id=\"$instance_id\"})",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "RPC Inputs",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 5, "x": 8, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(id) (dayz_metricz_rpc_input_total{instance=\"$instance\", instance_id=\"$instance_id\"})",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "RPC Inputs",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 11, "x": 13, "y": 141 },
     "targets": [
      {
       "expr": "rate(dayz_metricz_rpc_input_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__rate_interval])",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Path Graph Updates",
     "type": "stat",
     "description": "Total updates path graph regions by object in the world",
     "gridPos": { "h": 5, "w": 5, "x": 8, "y": 152 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_path_graph_updates_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    }
   ]
  }
 ]
}