{
 "title": "MetricZ Servers Overview",
 "description": "Servers overview detailed stats for MetricZ",
 "tags": [
  "dayz",
  "metricz"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status,world)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},instance_id)"
    }
   },
   {
    "name": "scrape_interval",
    "label": "Scrape Interval",
    "query": {
     "query": "query_result(max(dayz_metricz_scrape_interval_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}))"
    }
   },
   { "name": "player_dash", "label": "Player Dashboard", "query": "cf1vdc82xx1q8e" },
   { "name": "server_dash", "label": "Server Dashboard", "query": "ff1kp4nh3cfeod" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_status{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Server uptime since start",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_uptime_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Update Duration",
   "type": "stat",
   "description": "Metrics update duration in game server",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(instance, instance_id, world) (dayz_metricz_update_duration_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Server FPS Average",
   "type": "timeseries",
   "description": "Average FPS over scrape window",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "dayz_metricz_fps_window_avg{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Players Alive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "dayz_metricz_players_online{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    },
    {
     "expr": "max(dayz_metricz_max_players{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "Players limit"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Server FPS Min",
   "type": "timeseries",
   "description": "Min FPS over scrape window",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "dayz_metricz_fps_window_min{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Server FPS Last",
   "type": "timeseries",
   "description": "Mission updates per one second (per one scrape)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "dayz_metricz_fps{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Server FPS Max",
   "type": "timeseries",
   "description": "Max FPS over scrape window",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "dayz_metricz_fps_window_max{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Infected Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "dayz_metricz_infected{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Animals Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "dayz_metricz_animals{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Items Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "dayz_metricz_items{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Infected Deaths Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_infected_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Animals Death Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_animals_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Transport Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "cars | {{instance_id}}"
    },
    {
     "expr": "dayz_metricz_boats{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "boats | {{instance_id}}"
    },
    {
     "expr": "dayz_metricz_helicopters{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "heli | {{instance_id}}"
    }
   ]
  },
  { "title": "RPC, Events and PathGraph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Average Rate of RPC Inputs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(id) (rate(dayz_metricz_rpc_input_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Average Rate of Server Events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(event) (rate(dayz_metricz_events_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "RPC Inputs Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance_id, world) (dayz_metricz_rpc_input_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Path Graph Updates Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_path_graph_updates_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Events Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance_id, world) (dayz_metricz_events_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Path Graph Updates Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_path_graph_updates_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  { "title": "Players", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Players List",
   "type": "table",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{ world }} ({{ instance_id }}) - {{ steam_id }}"
    }
   ]
  },
  {
   "title": "Average Ping of all Players",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "min(dayz_metricz_player_network_ping_min{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "min"
    },
    {
     "expr": "max(dayz_metricz_player_network_ping_max{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "max"
    },
    {
     "expr": "(\r\n  min(dayz_metricz_player_network_ping_min{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})\r\n  +\r\n  max(dayz_metricz_player_network_ping_max{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})\r\n) / 2",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Players Spawn Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_players_spawns_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "God Mode Players",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "group by(steam_id) (dayz_metricz_player_godmode{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0)",
     "legendFormat": "{{ steam_id }}"
    }
   ]
  },
  {
   "title": "Players Deaths Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_players_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players Death Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_players_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players Corpses Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "dayz_metricz_corpses{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  { "title": "Infected", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Infected Types Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by(type) (dayz_metricz_infected_by_type{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Infected Corpses",
   "type": "timeseries",
   "description": "Corpses on ground",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "dayz_metricz_infected_dead_bodies{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Infected Mind States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "dayz_metricz_infected_mind_state{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{ state }} | {{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Infected Mind State Change Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_infected_mind_state{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{ state }} | {{world}} ({{instance_id}})"
    }
   ]
  },
  { "title": "Animals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Animal Types Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "sum by(animal) (dayz_metricz_animals_by_type{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}) > 0",
     "legendFormat": "{{animal}}"
    }
   ]
  },
  {
   "title": "Animal Corpses",
   "type": "timeseries",
   "description": "Corpses on ground",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "dayz_metricz_animals_dead_bodies{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "AI/NPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "collapsed": true,
   "panels": [
    {
     "title": "AI Count",
     "type": "timeseries",
     "description": "Active AI",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
     "targets": [
      {
       "expr": "dayz_metricz_eai{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "AI NPC Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
     "targets": [
      {
       "expr": "dayz_metricz_eai_npc{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Weapons, magazines, explosives, ammunition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 }
  },
  {
   "title": "Weapons Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_weapons{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Magazines Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_magazines{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Optics Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_optics{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Suppressors Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_suppressors{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Ammo Piles Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_ammo{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Ammo Boxes Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_ammo_boxes{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Explosives Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_explosives{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Explosives Detonated Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_explosives_detonated_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  { "title": "Weapon Types Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 182 } },
  {
   "title": "Weapons Types Total",
   "type": "bargauge",
   "gridPos": { "h": 26, "w": 5, "x": 0, "y": 183 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(weapon) (dayz_metricz_weapons_by_type{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0)",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  {
   "title": "Weapons Types Total",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 19, "x": 5, "y": 183 },
   "targets": [
    {
     "expr": "sum by(weapon) (dayz_metricz_weapons_by_type{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0)",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  { "title": "Weapon Shots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 } },
  {
   "title": "Weapons Shots Total by Weapon",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 210 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (weapon) (increase(dayz_metricz_weapon_shots_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__range])) > 0",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  {
   "title": "Weapons Shots Rate by Weapon",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 10, "x": 5, "y": 210 },
   "targets": [
    {
     "expr": "sum by(weapon) (rate(dayz_metricz_weapon_shots_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])) > 0",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  {
   "title": "Weapons Shots Rate by Instance",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 210 },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (rate(dayz_metricz_weapon_shots_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "Weapons Shots Total by Instance",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 220 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, instance_id, world) (dayz_metricz_weapon_shots_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{world}} ({{ instance_id}})"
    }
   ]
  },
  { "title": "Kills by Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 } },
  {
   "title": "Player Killed",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 231 },
   "targets": [
    {
     "expr": "sum by (weapon) (increase(dayz_metricz_player_killed_by_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__range]) > 0)",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  {
   "title": "Creature Killed",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 231 },
   "targets": [
    {
     "expr": "sum by (weapon) (increase(dayz_metricz_creature_killed_by_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__range]) > 0)",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  { "title": "Hits by Ammo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 } },
  {
   "title": "Player Hits",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 249 },
   "targets": [
    {
     "expr": "sum by (ammo) (increase(dayz_metricz_player_hit_by_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__range]) > 0)",
     "legendFormat": "{{ammo}}"
    }
   ]
  },
  {
   "title": "Creature Hits",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 249 },
   "targets": [
    {
     "expr": "sum by (ammo) (increase(dayz_metricz_creature_hit_by_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__range]) > 0)",
     "legendFormat": "{{ammo}}"
    }
   ]
  },
  { "title": "Food", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 266 } },
  {
   "title": "Food Types Total",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 267 },
   "targets": [
    {
     "expr": "sum by(food_type) (dayz_metricz_food{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", food_type!=\"\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Bases and Buildings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 283 } },
  {
   "title": "Territory Flags Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 284 },
   "targets": [
    {
     "expr": "dayz_metricz_territory_lifetime{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{x}}/{{z}} | {{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Base Buildings",
   "type": "timeseries",
   "description": "BaseBuildingBase (Fence, Watchtower, ShelterSite, TerritoryFlag, etc)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 284 },
   "targets": [
    {
     "expr": "dayz_metricz_base_buildings{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Stashes",
   "type": "timeseries",
   "description": "Digged items (DrysackBag, SeaChest, WoodenCrate, FirstAidKit, AmmoBox, Pot, Bear, etc.)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 293 },
   "targets": [
    {
     "expr": "dayz_metricz_stashes{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Dug Garden Plots",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 293 },
   "targets": [
    {
     "expr": "dayz_metricz_gardens{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Tents",
   "type": "timeseries",
   "description": "TentBase (Shelter, CarTent, LargeTent, PartyTent, MediumTent)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 293 },
   "targets": [
    {
     "expr": "dayz_metricz_tents{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  { "title": "Effect Areas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 302 } },
  {
   "title": "Effect Area by Type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 303 },
   "targets": [
    {
     "expr": "count by (type) (dayz_metricz_effect_area_insiders{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effect Area Insiders Max",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 303 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (class) (increase(dayz_metricz_effect_area_insiders{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__range]) > 0)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Effect Area by Class",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 303 },
   "targets": [
    {
     "expr": "count by (class) (dayz_metricz_effect_area_insiders{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "World Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 313 } },
  {
   "title": "Players Alive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "Players" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_players_online{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "📅 Game Date and Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 318 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_game_time_unix_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} * 1000",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "🌙 Time of Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 321 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_time_of_day{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "🌡️ Temperature Feels Like",
   "type": "stat",
   "description": "Point in center of world with overcast, wind and fog components",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 325 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_temperature{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "💨 Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_wind_speed{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "🌧️ Rain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 333 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_rain{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{ world }} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "❄️ Snow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 337 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_snow{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{ world }} ({{ instance_id }})"
    }
   ]
  },
  {
   "title": "🌫️Fog",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 341 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_fog{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{ instance_id }})"
    }
   ]
  }
 ]
}