{
 "title": "MetricZ Transport",
 "description": "Transport detailed stats for MetricZ",
 "tags": [
  "dayz",
  "metricz"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status{instance=~\"$instance\"},world)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{instance=~\"$instance\", world=~\"$instance_id|$world\"},instance_id)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(dayz_metricz_transport_health{instance=~\"$instance\", world=~\"$instance_id|$world\"},type)"
    }
   },
   {
    "name": "hash",
    "label": "Hash",
    "query": {
     "query": "label_values(dayz_metricz_transport_health{instance=~\"$instance\", world=~\"$instance_id|$world\", instance_id=~\"$instance_id\", type=~\"$type\"},hash)"
    }
   },
   {
    "name": "class",
    "label": "Class",
    "query": {
     "query": "label_values(dayz_metricz_transport_health{instance=~\"$instance\", world=~\"$instance_id|$world\", instance_id=~\"$instance_id\", type=~\"$type\", hash!=\"$hash\"},class)"
    }
   },
   { "name": "map_tiles_layer", "label": "Map Tiles Layer", "query": "topographic,satellite" },
   {
    "name": "map_tiles_url",
    "label": "Map Tiles URL",
    "query": "https://dzmap.woozymasta.ru/maps"
   },
   {
    "name": "scrape_interval",
    "label": "Scrape Interval",
    "query": {
     "query": "query_result(max(dayz_metricz_scrape_interval_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transport Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}} {{world}} cars"
    },
    {
     "expr": "dayz_metricz_boats{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}} {{world}} boats"
    },
    {
     "expr": "dayz_metricz_helicopters{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}} {{world}} heli"
    }
   ]
  },
  {
   "title": "Transport Health",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dayz_metricz_transport_health{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", type=~\"$type\", hash=~\"$hash\", class=~\"$class\"}",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Transport Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "dayz_metricz_transport_speed{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", type=~\"$type\", hash=~\"$hash\", class=~\"$class\"}* 3.6",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Crew Occupied",
   "type": "timeseries",
   "description": "Number of occupied seats in transport",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "dayz_metricz_transport_crew_occupied{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", type=~\"$type\", hash=~\"$hash\", class=~\"$class\"}",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Engine On",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "dayz_metricz_transport_engine_on{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", type=~\"$type\", hash=~\"$hash\", class=~\"$class\"}",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Fuel Fraction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dayz_metricz_transport_fuel_fraction{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", type=~\"$type\", hash=~\"$hash\", class=~\"$class\"}",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Transport Speed",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "last_over_time(dayz_metricz_transport_health{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", type=~\"$type\", hash=~\"$hash\", class=~\"$class\"}[$__range])",
     "legendFormat": "{{class}}"
    }
   ]
  }
 ]
}