{
 "title": "MetricZ Player",
 "description": "Per player detailed stats for MetricZ",
 "tags": [
  "dayz",
  "metricz"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status{instance=~\"$instance\"},world)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},instance_id)"
    }
   },
   {
    "name": "steam_id",
    "label": "Steam ID",
    "query": {
     "query": "label_values(dayz_metricz_player_loaded,steam_id)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   {
    "name": "gender",
    "label": "Gender",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   {
    "name": "guid",
    "label": "GUID",
    "query": {
     "query": "label_values(dayz_metricz_player_loaded{steam_id=\"$steam_id\"},guid)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   },
   {
    "name": "blood",
    "label": "Blood",
    "query": {
     "query": "query_result(dayz_metricz_player_loaded{steam_id=\"$steam_id\"} @ end() or  last_over_time(dayz_metricz_player_loaded{steam_id=\"$steam_id\"}[$__range]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players List",
   "type": "table",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by(steam_id, name) (dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "{{ world }} ({{ instance_id }}) - {{ steam_id }}"
    }
   ]
  },
  {
   "title": "Plyer Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": {
    "content": "![${type}](https://raw.githubusercontent.com/WoozyMasta/metricz/refs/heads/master/avatars/${type}.png)\n\n## [${name}](https://steamcommunity.com/profiles/${steam_id})\n\n${type} (${gender}) ${blood} `${steam_id}`\n\n`${guid}`"
   }
  },
  {
   "title": "Session Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_lifetime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}\r\nor\r\nlast_over_time(dayz_metricz_player_lifetime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}[$__range])\r\n",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_health{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Blood",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_blood{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Shock",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_shock{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Life Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_stat_playtime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}\r\nor\r\nlast_over_time(dayz_metricz_player_stat_playtime_seconds{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\",steam_id=\"$steam_id\"}[$__range])",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_energy{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Water",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_water{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Toxicity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_toxicity{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Infected Killed Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "dayz_metricz_player_stat_infected_killed_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Distance Traveled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "dayz_metricz_player_stat_distance_meters{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Network Ping",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "dayz_metricz_player_network_ping_min{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "min"
    },
    {
     "expr": "dayz_metricz_player_network_ping_max{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Players Killed Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "dayz_metricz_player_stat_players_killed_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Longest Survivor Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "dayz_metricz_player_stat_longest_survivor_hit_m{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_temperature_celsius{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Wetness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_wetness{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_weight{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Bleeding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_bleeding_active{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_agents_active{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Immunity Boosted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_immunity_boosted{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Session Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dayz_metricz_player_network_throttle{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "throttle"
    }
   ]
  },
  {
   "title": "Restrained",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_restrained{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Unconscious",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_unconscious{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "God Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_godmode{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Third Person",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_player_third_person{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\", steam_id=\"$steam_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  }
 ]
}