{
 "title": "MetricZ Server",
 "description": "DayZ server metrics",
 "tags": [ "dayz" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{instance=\"$instance\"},instance_id)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status{instance_id=\"$instance_id\", instance=\"$instance\"},world)"
    }
   },
   {
    "name": "save_version",
    "label": "Save Version",
    "query": {
     "query": "label_values(dayz_metricz_status{instance_id=\"$instance_id\", instance=\"$instance\"},save_version)"
    }
   },
   {
    "name": "game_version",
    "label": "Game Version",
    "query": {
     "query": "label_values(dayz_metricz_status{instance_id=\"$instance_id\", instance=\"$instance\"},game_version)"
    }
   },
   {
    "name": "scrape_interval",
    "label": "Scrape Interval",
    "query": {
     "query": "query_result(dayz_metricz_scrape_interval_seconds{instance=\"$instance\", instance_id=\"$instance_id\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_status{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Server FPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_fps{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    },
    {
     "expr": "max(dayz_metricz_fps_limit{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Players Spawn",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Spawn" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dayz_metricz_players_spawns_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players Alive",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Players" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_players_online{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    },
    {
     "expr": "dayz_metricz_max_players{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players Corpses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Corpses" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_corpses{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Players Death",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Death" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_players_deaths_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Items",
   "type": "stat",
   "description": "ItemBase",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_items{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Transport",
   "type": "stat",
   "description": "Edible_Base",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=\"$instance\",instance_id=\"$instance_id\"} + dayz_metricz_boats{instance=\"$instance\",instance_id=\"$instance_id\"} + dayz_metricz_helicopters{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "AI",
   "type": "stat",
   "description": "ZomieBase + AnimalBase",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_infected{instance=\"$instance\",instance_id=\"$instance_id\"} + dayz_metricz_animals{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Weapon Shoots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weapon_shots_all_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Game version",
   "type": "text",
   "description": "Game version (save version)",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "## **${world}** ${game_version} `${save_version}`"
   }
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 } },
  {
   "title": "Update Duration",
   "type": "stat",
   "description": "Metrics update duration in game server",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_update_duration_seconds{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Metrics Skipped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_scrape_skipped_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "AI Count",
   "type": "timeseries",
   "description": "Include death bodies",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "dayz_metricz_infected{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "infected"
    },
    {
     "expr": "dayz_metricz_animals{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "animal"
    }
   ]
  },
  {
   "title": "AI Deaths",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Deaths" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_infected_deaths_total{instance_id=\"$instance_id\"}",
     "legendFormat": "infected"
    },
    {
     "expr": "dayz_metricz_animals_deaths_total{instance_id=\"$instance_id\"}",
     "legendFormat": "animals"
    }
   ]
  },
  {
   "title": "Clothes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_clothes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Food",
   "type": "stat",
   "description": "Edible_Base",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_food{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Bottles",
   "type": "stat",
   "description": "Bottle_Base",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_bottles{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Car Parts",
   "type": "stat",
   "description": "doors & trunks",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_car_parts{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Weapons",
   "type": "stat",
   "description": "Weapon_Base",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weapons{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Ammo Piles",
   "type": "stat",
   "description": "Ammunition_Base",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_ammo{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Ammo Boxes",
   "type": "stat",
   "description": "Total Box_Base with Ammo",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_ammo_boxes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Magazines",
   "type": "stat",
   "description": "MagazineStorage",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_magazines{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Server Envents",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (dayz_metricz_events_total{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Game date and time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_game_time_unix_seconds{instance=\"$instance\",instance_id=\"$instance_id\"} * 1000",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Feels like",
   "type": "stat",
   "description": "Point in center of world with overcast, wind and fog components",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_temperature{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Base world temperature",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_temperature_base{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Transport Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world }} ({{instance_id}})"
    },
    {
     "expr": "dayz_metricz_boats{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world }} ({{instance_id}})"
    },
    {
     "expr": "dayz_metricz_helicopters{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world }} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Transport destoroyed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Destroyed" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_cars_destroyed_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "Cars"
    },
    {
     "expr": "dayz_metricz_boats_destroyed_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "Boats"
    },
    {
     "expr": "dayz_metricz_helicopters_destroyed_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "Helicopters"
    }
   ]
  },
  {
   "title": "Explosives",
   "type": "stat",
   "description": "grenade, flash, smoke, claymore, plastic, improvised",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_explosives{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Tents",
   "type": "stat",
   "description": "TentBase (Shelter, CarTent, LargeTent, PartyTent, MediumTent)",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_tents{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "DeployableContainer_Base (Barrel, SeaChest, WoodenCrate)",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_containers{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Boxes",
   "type": "stat",
   "description": "NailBox, HeadlightH7_Box",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_boxes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_wind_speed{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_wind_direction{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Base Buildings",
   "type": "stat",
   "description": "BaseBuildingBase (Fence, Watchtower, ShelterSite, TerritoryFlag, etc)",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_base_buildings{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Territory Flag",
   "type": "stat",
   "description": "TerritoryFlag",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_territory_flags{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Stashes",
   "type": "stat",
   "description": "Digged items (DrysackBag, SeaChest, WoodenCrate, FirstAidKit, AmmoBox, Pot, Bear, etc.)",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_stashes{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Gardens",
   "type": "stat",
   "description": "GardenPlot (Digged)",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_gardens{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Time of Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_time_of_day{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Clouds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_clouds{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Weapons Shoots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 21 },
   "targets": [
    {
     "expr": "dayz_metricz_weapon_shots_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{weapon}}"
    }
   ]
  },
  {
   "title": "Crash Sites",
   "type": "stat",
   "description": "mi8, uh1y, santa sleigh",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_crash_sites{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Artillery Strikes",
   "type": "stat",
   "description": "Artillery barrages on server",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_artillery_barrages_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Fishing Attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_fishing_attempts_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Fishing Catches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_fishing_catches_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Fog",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_weather_fog{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Rain/Snow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(dayz_metricz_weather_rain{instance=\"$instance\",instance_id=\"$instance_id\"}, 0.0001)",
     "legendFormat": "rain"
    },
    {
     "expr": "clamp_min(dayz_metricz_weather_snow{instance=\"$instance\",instance_id=\"$instance_id\"}, 0.0001)",
     "legendFormat": "snow"
    }
   ]
  },
  {
   "title": "Mined Bushes",
   "type": "stat",
   "description": "Increment per one action usage",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_mined_bushes_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Mined Rocks",
   "type": "stat",
   "description": "Increment per one action usage",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_mined_rocks_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Mined Trees",
   "type": "stat",
   "description": "Increment per one action usage",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_mined_trees_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Gifts Unpacked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_gifts_unpacked_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Path Graph Updates",
   "type": "stat",
   "description": "Total updates path graph regions by object in the world",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_path_graph_updates_total{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Territory Lifetime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 29 },
   "targets": [
    {
     "expr": "dayz_metricz_territory_lifetime{instance=\"$instance\",instance_id=\"$instance_id\"}",
     "legendFormat": "{{x}}/{{z}}"
    }
   ]
  },
  {
   "title": "RPC Inputs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_rpc_input_total{instance=\"$instance\",instance_id=\"$instance_id\"}[$__rate_interval])",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "RPC Inputs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(id) (dayz_metricz_rpc_input_total{instance=\"$instance\",instance_id=\"$instance_id\"})",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}