{
 "title": "MetricZ Servers Overview",
 "description": "Servers overview detailed stats for MetricZ",
 "tags": [
  "dayz",
  "metricz"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dayz_metricz_status,instance)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(dayz_metricz_status,world)"
    }
   },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(dayz_metricz_status{world=~\"$world\"},instance_id)"
    }
   },
   {
    "name": "scrape_interval",
    "label": "Scrape Interval",
    "query": {
     "query": "query_result(max(dayz_metricz_scrape_interval_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}))"
    }
   },
   { "name": "player_dash", "label": "Player Dashboard", "query": "cf1vdc82xx1q8e" },
   { "name": "server_dash", "label": "Server Dashboard", "query": "ff1kp4nh3cfeod" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_status{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Server uptime since start",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_uptime_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Update Duration",
   "type": "stat",
   "description": "Metrics update duration in game server",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "dayz_metricz_update_duration_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Server FPS Average",
   "type": "timeseries",
   "description": "Average FPS over scrape window",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "dayz_metricz_fps_window_avg{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}} {{world}}"
    }
   ]
  },
  {
   "title": "Players Alive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "dayz_metricz_players_online{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{world}} ({{instance_id}})"
    },
    {
     "expr": "max(dayz_metricz_max_players{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
     "legendFormat": "Players limit"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Server FPS Min",
   "type": "timeseries",
   "description": "Min FPS over scrape window",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "dayz_metricz_fps_window_min{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Server FPS Last",
   "type": "timeseries",
   "description": "Mission updates per one second (per one scrape)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "dayz_metricz_fps{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Server FPS Max",
   "type": "timeseries",
   "description": "Max FPS over scrape window",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "dayz_metricz_fps_window_max{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Infected Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "dayz_metricz_infected{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Animals Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "dayz_metricz_animals{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Items Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "dayz_metricz_items{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Infected Deaths Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_infected_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Animals Death Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "rate(dayz_metricz_animals_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "Transport Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "dayz_metricz_cars{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "cars | {{instance_id}}"
    },
    {
     "expr": "dayz_metricz_boats{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "boats | {{instance_id}}"
    },
    {
     "expr": "dayz_metricz_helicopters{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
     "legendFormat": "heli | {{instance_id}}"
    }
   ]
  },
  {
   "title": "RPC, Events and PathGraph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Rate of RPC Inputs",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(id) (rate(dayz_metricz_rpc_input_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Average Rate of Server Events",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(event) (rate(dayz_metricz_events_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
       "legendFormat": "{{ event }}"
      }
     ]
    },
    {
     "title": "RPC Inputs Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance_id, world) (dayz_metricz_rpc_input_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Path Graph Updates Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "rate(dayz_metricz_path_graph_updates_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
       "legendFormat": "{{instance_id}} {{world}}"
      }
     ]
    },
    {
     "title": "Events Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance_id, world) (dayz_metricz_events_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Path Graph Updates Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_path_graph_updates_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Players",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 296 },
     "targets": [
      {
       "expr": "dayz_metricz_player_loaded{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{ world }} ({{ instance_id }}) - {{ steam_id }}"
      }
     ]
    },
    {
     "title": "Players Deaths Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 296 },
     "targets": [
      {
       "expr": "rate(dayz_metricz_players_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Players Death Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 303 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_players_deaths_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Players Corpses Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 306 },
     "targets": [
      {
       "expr": "dayz_metricz_corpses{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Players Spawn Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 12, "y": 313 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_players_spawns_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "3rd person vs 1st person view",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 17, "y": 313 },
     "targets": [
      {
       "expr": "count(\r\n  avg by (steam_id) (\r\n    avg_over_time(dayz_metricz_player_third_person{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\"}[$__range])\r\n  ) <= 0.5\r\n)",
       "legendFormat": "1rd"
      },
      {
       "expr": "count(\r\n  avg by (steam_id) (\r\n    avg_over_time(dayz_metricz_player_third_person{instance=~\"$instance\",instance_id=~\"$instance_id\",world=~\"$world\"}[$__range])\r\n  ) > 0.5\r\n)",
       "legendFormat": "3rd"
      }
     ]
    },
    {
     "title": "Good Mode Players",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 313 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "group by(steam_id) (dayz_metricz_player_godmode{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0)",
       "legendFormat": "{{ steam_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infected Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 387 },
     "targets": [
      {
       "expr": "dayz_metricz_infected{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} > 0",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Infected Mind States",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 395 },
     "targets": [
      {
       "expr": "dayz_metricz_infected_mind_state{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{ state }} | {{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Infected Mind State Change Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 395 },
     "targets": [
      {
       "expr": "rate(dayz_metricz_infected_mind_state{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval])",
       "legendFormat": "{{ state }} | {{world}} ({{instance_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Firearms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Weapons Shoots Total by Weapon",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 0, "y": 578 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(weapon) (dayz_metricz_weapon_shots_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{weapon}}"
      }
     ]
    },
    {
     "title": "Weapons Shoots Rate by Weapon",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 5, "y": 578 },
     "targets": [
      {
       "expr": "sum by(weapon) (rate(dayz_metricz_weapon_shots_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
       "legendFormat": "{{weapon}}"
      }
     ]
    },
    {
     "title": "Weapons Shoots Total by Instance",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 12, "y": 578 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_weapon_shots_all_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id}})"
      }
     ]
    },
    {
     "title": "Weapons Shoots Rate by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 578 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (rate(dayz_metricz_weapon_shots_all_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}[$__rate_interval]))",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "Weapons Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 588 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_weapons{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "Explosives Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 588 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_explosives{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "Explosives Detonated Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 588 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_explosives_detonated_total{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "Magazines Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 597 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_magazines{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "Ammo Piles Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 597 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_ammo{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "Ammo Boxes Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 597 },
     "targets": [
      {
       "expr": "sum by(instance, instance_id, world) (dayz_metricz_ammo_boxes{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"})",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Bases and Buildings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Territory Flags Lifetime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 406 },
     "targets": [
      {
       "expr": "dayz_metricz_territory_lifetime{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{x}}/{{z}} | {{instance_id}} {{world}}"
      }
     ]
    },
    {
     "title": "Base Buildings",
     "type": "timeseries",
     "description": "BaseBuildingBase (Fence, Watchtower, ShelterSite, TerritoryFlag, etc)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 406 },
     "targets": [
      {
       "expr": "dayz_metricz_base_buildings{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{instance_id}} {{world}}"
      }
     ]
    },
    {
     "title": "Stashes",
     "type": "timeseries",
     "description": "Digged items (DrysackBag, SeaChest, WoodenCrate, FirstAidKit, AmmoBox, Pot, Bear, etc.)",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 415 },
     "targets": [
      {
       "expr": "dayz_metricz_stashes{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{instance_id}} {{world}}"
      }
     ]
    },
    {
     "title": "Digged Garden Plots",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 415 },
     "targets": [
      {
       "expr": "dayz_metricz_gardens{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{instance_id}} {{world}}"
      }
     ]
    },
    {
     "title": "Tents",
     "type": "timeseries",
     "description": "TentBase (Shelter, CarTent, LargeTent, PartyTent, MediumTent)",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 415 },
     "targets": [
      {
       "expr": "dayz_metricz_tents{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{instance_id}} {{world}}"
      }
     ]
    }
   ]
  },
  {
   "title": "World Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Players Alive",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 425 },
     "fieldConfig": { "defaults": { "unit": "Players" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_players_online{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "📅 Game Date and Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 429 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_game_time_unix_seconds{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"} * 1000",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "🌙 Time of Day",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 432 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_time_of_day{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "🌡️ Temperature Feels Like",
     "type": "stat",
     "description": "Point in center of world with overcast, wind and fog components",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_temperature{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "💨 Wind Speed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 440 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_wind_speed{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "🌧️ Rain",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 444 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_rain{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{ world }} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "❄️ Snow",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 448 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_snow{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{ world }} ({{ instance_id }})"
      }
     ]
    },
    {
     "title": "🌫️Fog",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 452 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "dayz_metricz_weather_fog{instance=~\"$instance\", instance_id=~\"$instance_id\", world=~\"$world\"}",
       "legendFormat": "{{world}} ({{ instance_id }})"
      }
     ]
    }
   ]
  }
 ]
}